### ISSUE TITLE
City processing not working as expected

### ISSUE THREAD

**Issue by lochnesh** [kschlorff16/get-ze-weather#1]
Hello,

There are a couple test scenarios which are not returning the expected results

Example #1 - A space occurs after the comma

When a space occurs after the city name, the program exits unexpectedly.  

```
⇒  ./get-ze-weather
Where are you?
Ames,Iowa
Ames weather:
66.97 degrees Fahrenheit

⇒  ./get-ze-weather
Where are you?
Ames, Iowa
```

Example #2 - A city with a space in the name 

When a space occurs in the city name (example Des Moines), only the first word is evaluated as the city.

```
⇒  ./get-ze-weather
Where are you?
Des Moines
Des weather:
59.09 degrees Fahrenheit

⇒  ./get-ze-weather
Where are you?
Des
Des weather:
59.09 degrees Fahrenheit
```

**Comment by kschlorff16** [comment]
The second bug was addressed with c6f1e42c653303129a4e5eed1afefa5e36d03ac7
